export const styles = {
  filterCard: {
    background: '#ffffff',
    padding: '20px',
    border: '1px solid #e2e8f0',
    borderRadius: 'var(--radius-lg)',
    boxShadow: 'var(--shadow-card)',
    marginBottom: '24px',
  },
  label: {
    display: 'block',
    fontFamily: 'var(--apple-font-display)',
    fontSize: '12px',
    fontWeight: 500,
    color: '#64748B',
    textTransform: 'none' as const,
    letterSpacing: 'normal',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #e2e8f0',
    borderRadius: 'var(--radius-lg)',
    fontFamily: 'var(--apple-font-display)',
    fontSize: '14px',
    background: '#f8fafc',
    outline: 'none',
  },
  primaryButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    background: '#0F172A',
    color: 'white',
    border: 'none',
    borderRadius: 'var(--radius-lg)',
    fontFamily: 'var(--apple-font-display)',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    textDecoration: 'none',
    textTransform: 'none' as const,
    letterSpacing: 'normal',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: '16px',
  },
   tableContainer: {
    marginTop: '32px',
    border: '1px solid #e2e8f0',
    background: 'white',
    overflowX: 'auto' as const,
    borderRadius: 'var(--radius-lg)',
    boxShadow: 'var(--shadow-card)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '13px',
    fontFamily: 'var(--apple-font-display)',
  },
  th: {
    background: '#f8fafc',
    borderBottom: '2px solid #e2e8f0',
    padding: '12px 16px',
    textAlign: 'left' as const,
    fontFamily: 'var(--apple-font-display)',
    fontSize: '12px',
    fontWeight: 600,
    color: '#64748B',
    textTransform: 'none' as const,
    letterSpacing: 'normal',
  },
  td: {
    padding: '12px 16px',
    borderBottom: '1px solid #e2e8f0',
    color: '#0F172A',
  },
  paginationContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px',
    background: '#ffffff',
    borderTop: '1px solid #e2e8f0',
  }
};
